services:
  - type: web
    name: algovote-frontend
    env: node
    region: singapore
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: algovote-backend
          envVarKey: RENDER_EXTERNAL_URL
    autoDeploy: true

  - type: web
    name: algovote-backend
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker -w 4 -b 0.0.0.0:$PORT app.main:app
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 8000
    autoDeploy: true 